[package]
name = "svd2html"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
svd-parser = "0.13.1"
clap = "3.0.7"
clap_derive = "3.0.6"
