[package]
name    = "svd2html"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow      = "1.0.53"
clap        = { version = "3.0.7",  features = ["derive"] }
lazy_static = "1.4.0"
minijinja   = { version = "0.13.0", features = ["source"] }
svd-parser  = "0.13.1"
